"""Generate docs/configuration.md from the settings metadata in eye_tracker.config.

Usage:
    uv run python scripts/gen_config_docs.py          # rewrite the page
    uv run python scripts/gen_config_docs.py --check  # exit 1 if the page is out of date

The output does not depend on the platform it is generated on (hotkey defaults
are listed for every platform), so CI can check it anywhere.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from eye_tracker import config  # noqa: E402

OUTPUT = ROOT / "docs" / "configuration.md"

SECTION_TITLES = {
    "general": "General",
    "camera": "Camera",
    "performance": "Performance",
    "switching": "Switching",
    "presence": "Walk-away (presence)",
    "privacy": "Privacy",
    "hotkeys": "Hotkeys",
    "learning": "Learning",
    "ui": "Interface",
}

HEADER = """# Configuration reference

Every option can be changed in **Settings** (tray menu). They are stored in `settings.json`, whose
location `eye-tracker doctor` prints. Unknown keys are ignored, missing keys use the defaults below,
and out-of-range values are clamped, so a hand-edited file can never stop the app from starting.

<!-- Generated by scripts/gen_config_docs.py from eye_tracker.config; do not edit by hand. -->
"""


def _code(value: Any) -> str:
    return f"`{value}`"


def _default(key: str, value: Any) -> str:
    if key.startswith("hotkeys.") and isinstance(value, str) and "+" in value:
        letter = value.rsplit("+", 1)[1]
        platforms = [
            ("Windows", config._HOTKEY_MODIFIERS.get("win32", config._HOTKEY_MODIFIERS_OTHER)),
            ("macOS", config._HOTKEY_MODIFIERS.get("darwin", config._HOTKEY_MODIFIERS_OTHER)),
            ("Linux", config._HOTKEY_MODIFIERS_OTHER),
        ]
        return "<br>".join(f"{_code(f'{mods}+{letter}')} {name}" for name, mods in platforms)
    if isinstance(value, bool):
        return _code("true" if value else "false")
    if isinstance(value, list):
        return _code(", ".join(value)) if value else _code("[]")
    return _code(value)


def _allowed(row: dict[str, Any]) -> str:
    if row["choices"]:
        return " · ".join(_code(c) for c in row["choices"])
    lo, hi = row["lo"], row["hi"]
    if lo is None and hi is None:
        return ""

    def num(v: float) -> str:
        return str(int(v)) if float(v).is_integer() else str(v)

    return f"{num(lo)} – {num(hi)}"


def render() -> str:
    lines = [HEADER]
    current = None
    for row in config.describe_settings():
        section = row["key"].split(".", 1)[0]
        if section != current:
            current = section
            lines += [
                f"\n## {SECTION_TITLES.get(section, section.title())}\n",
                "| Key | Default | Allowed | Description |",
                "|---|---|---|---|",
            ]
        doc = " ".join(str(row["doc"] or "").split()).replace("|", "\\|")
        lines.append(
            f"| {_code(row['key'])} | {_default(row['key'], row['default'])} "
            f"| {_allowed(row)} | {doc} |"
        )
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the page is out of date")
    args = parser.parse_args(argv)
    text = render()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != text:
            print("docs/configuration.md is out of date; run scripts/gen_config_docs.py")
            return 1
        print("docs/configuration.md is up to date")
        return 0
    OUTPUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
